version: '2'
services:
  db:
    image: postgres-with-pgq
    build:
      context: ./
      dockerfile: ./db/Dockerfile
    ports:
      - '5432:5432'
    volumes:
      - './db/src:/docker-entrypoint-initdb.d'
    environment:
      - POSTGRES_USER=${SUPER_USER}
      - POSTGRES_PASSWORD=${SUPER_USER_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - SUPER_USER=${SUPER_USER}
      - SUPER_USER_PASSWORD=${SUPER_USER_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672' # management web ui
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      
  mikkoo:
    image: mikkoo
    build:
      context: ./mikkoo
      dockerfile: ./Dockerfile
    environment:
      - AMQP_HOST=rabbitmq
      - AMQP_PASS=${RABBITMQ_DEFAULT_PASS}
      - AMQP_USER=${RABBITMQ_DEFAULT_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${SUPER_USER_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${SUPER_USER}
    depends_on:
      - rabbitmq
      - db
    restart: unless-stopped
